added annotator analyzer cronjob
Surveily/cvat pull request #1
Opened 2023-04-19 10:50 UTC by Sumered

2023-04-19 10:59 UTC, turowicz approved these changes

2023-05-23 08:57 UTC, kbegiedza requested changes

2023-05-23 08:57 UTC, bknulz commented on helm-chart/templates/analytics/analyzer/storage.yml
> +      storage: 5Gi
Add as param

2023-05-23 08:57 UTC, bknulz commented on helm-chart/templates/analytics/analyzer/storage.yml
> +      storage: 5Gi
define in values

2023-05-23 08:57 UTC, kbegiedza commented on helm-chart/templates/analytics/analyzer/storage.yml
> +      storage: .Values.analytics.job.memory
missing {{  }}

try dry-run to debug

2023-05-23 11:39 UTC, kbegiedza approved these changes
LGTM

2023-05-23 11:40 UTC, turowicz commented
> LGTM

Lets Go To Moon

2023-05-23 16:45 UTC, merged